### PR TITLE
make http client configurable

### PR DESCRIPTION
**Pull request by ginabythebay**
Added the ability to configure what http client to use.  This is necessary, for example, on google app engine, where regular http connections are not allowed.

A side effect of this change is that it becomes easier to test, so I added a few of those too.

### CODE REVIEW

**Review by dinedal — APPROVED** [review]

**Comment by dinedal** [comment]
Thanks!

Would love to hear more about what you're using this for :)

**Comment by ginabythebay** [comment]
I'm poking at integrating google actions with nextbus (so I can ask my google home device when the next bus is).  I'm not sure yet if this will go anywhere useful.  I will need to figure out how to come up with something generally useful enough for google to approve the action and how to keep the nextbus api usage low enough not to trigger their rate limiting.

**Comment by dinedal** [comment]
>  I will need to figure out how to come up with something generally useful enough for google to approve the action and how to keep the nextbus api usage low enough not to trigger their rate limiting.

I use this project to feed my smart clock my local bus arrival time. I check every 20s and only get the exact stop I need, hard coded the IDs so there's no lookup. I also buffer the result in memory so if there's a failure I still keep the estimates around (but once they are a minute stale I evict them).

I suggest you do something similar, query only for what you need, no need to refresh constantly and keep a buffer around incase a request fails / times out so you can fall back on that.

If you're expecting a lot of use, probably better to sync the times to your own cache or buffer instead of querying on demand, otherwise you will go over the rate limits.

**Comment by ginabythebay** [comment]
Yeah.  I have been thinking along similar lines!

**Pull request merged**
